### ISSUE TITLE
slp not showing at screen and not added after winning a arena game (here is my eth address. 0xa074b3387cfe43e3a0585be2cc155904f59d3ab5)

### ISSUE THREAD

**Issue by jcmarilla** [axieinfinity/ronin-smart-contracts#20]
slp not showing after winning a arena game (i have energy but slp not showing at screen and not added at balance) 

https://user-images.githubusercontent.com/76611088/103148145-b8250600-4797-11eb-92bd-c5186006fd6e.mp4

**Comment by jcmarilla** [comment]
is this a bug???

**Comment by trungfinity** [comment]
Out of scope.
