### ISSUE TITLE
Three same card at one axie bug

### ISSUE THREAD

**Issue by jcmarilla** [axieinfinity/ronin-smart-contracts#22]
i encounter this bug at arena and pve match its possible to get 3 card at same axie? or its just a bug?  (my eth add. 0x76ADa82F4647a54421786b75970d37bf1c78F50D)
![IMG_20201226_223410](https://user-images.githubusercontent.com/76611088/103153310-b1fc4d00-47ca-11eb-8886-6f84587d5c31.jpg)
![IMG_20201226_222651_535](https://user-images.githubusercontent.com/76611088/103153314-b7f22e00-47ca-11eb-941f-8a37304e86e0.jpg)

**Comment by trungfinity** [comment]
Out of scope.
