### ISSUE TITLE
Could you provide RON and SLP testnet faucet ?

### ISSUE THREAD

**Issue by acinmavi** [axieinfinity/ronin-smart-contracts#38]
We are going to integrate RON and SLP support to our cryptor broker but when apply it on dev environment , we could not found any RON and SLP faucet . Could you provide some faucet for us ?
Or if possible , please send some testnet RON and SLP to testnet address 0xFd7eE97dbe47A19FB679f0af8e837145C76Ede6F so we could test and intergrate on dev.
Thanks.

**Comment by nosyajmagS020796** [comment]
Yes

**Comment by acinmavi** [comment]
Please never mind , we finished to implement with RON :D
