### ISSUE TITLE
Bug Bounty Program - Security Vulnerabilities

### ISSUE THREAD

**Issue by ugwst-sec** [axieinfinity/ronin-smart-contracts#43]
Hi all,

It would be nice if Axie Infinity put a bug bounty program in place, we tried reaching out to multiple members and teams - unsuccessfully.

There should be a reward table for contracts + web vulnerabilities(marketplace etc.).

Best,
UGWST.COM

**Comment by jhemmmm** [comment]
https://skymavis.notion.site/Sky-Mavis-Bug-Bounty-Program-ef33b18c4ee14eaab4698a8efd2c9992
